version: '3.8'

services:
  # Base de Datos MongoDB
  mongo:
    image: mongo:6.0
    container_name: summon_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo_data:/data/db

  # GUI Web para ver la BD (http://localhost:8081)
  mongo-express:
    image: mongo-express
    container_name: summon_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongo:27017/
    depends_on:
      - mongo

volumes:
  mongo_data: